### ISSUE TITLE
switch to yml

### ISSUE THREAD

**Issue by tolry** [larsborn/badge-batch#1]
Just a suggestion, might introduce other problems: but why not use http://symfony.com/doc/current/components/yaml/introduction.html to parse the 'txt'-file? Ok, with parsing yaml you might get more complex data structures than the simple hash map that is needed. But having a proven lib to do the parsing might have it's advantages too, when extending the file format later.

**Comment by larsborn** [comment]
after short consideration I might accept a PR for this one ;-)

I did my best to right quite unmaintainable code though. So good luck.

On the other hand I see a lot of potential in other (not yet created issues) so I'll prioritize different stuff.

**Comment by tolry** [comment]
Very clean and compact code so far, for what I have seen. Fishing for compliments: succesfull :smile:
